---
- hosts: all
  connection: local

  tasks:

    - name: Upload PDF to S3.
      s3: bucket='yourbucketnamehere' object=/cv.pdf src=/vagrant/cv.pdf mode=put overwrite=true
      environment:
        AWS_ACCESS_KEY: youraccesskeyhere
        AWS_SECRET_KEY: yoursecretkeyhere
